name: CI

on:
  push:

jobs:
  test:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-venv pipx 

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.3
          /root/.local/bin/poetry --version
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install project deps (including test extras)
        run: |
          poetry install --with test

      - name: Run test script
        run: |
          ./tests.sh

